import jsPDF from "jspdf";

export interface Generate2551QData {
  name: string;
  tin: string;
  quarter: number;
  gross: number;
  taxDue: number;
  date: string; // ISO date
}

const PESO = (n: number) => `PHP ${n.toLocaleString(undefined, { maximumFractionDigits: 2 })}`;

/**
 * Client-side quick-preview PDF for the /dashboard/forms "Quick 2551Q
 * Preview" card — NOT the official filing record. That real, quota-tracked,
 * watermarked-on-free-plan PDF lives in src/lib/pdf/generate-form-pdf.ts and
 * is served from /api/dashboard/forms/[id]/pdf; this one exists purely so a
 * user can see a rough tax-due preview and a scratch PDF without spending a
 * filing slot. Labeled "Quick Preview" throughout so the two are never
 * confused with each other.
 */
export function generate2551QPDF(data: Generate2551QData): Blob {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 40;

  // Dark header band
  doc.setFillColor(8, 15, 20); // #080F14
  doc.rect(0, 0, pageWidth, 92, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(34, 197, 94); // #22c55e
  doc.text("AXLA", margin, 40);
  doc.setFontSize(11);
  doc.setTextColor(255, 255, 255);
  doc.text("BIR Form 2551Q — Quarterly Percentage Tax (Quick Preview)", margin, 62);
  doc.setFontSize(8.5);
  doc.setTextColor(148, 163, 184);
  doc.text("Not an official BIR document — reference only. Confirm via eBIRForms before filing.", margin, 78);

  let y = 130;

  function row(label: string, value: string) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.setTextColor(100, 116, 139);
    doc.text(label, margin, y);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(15, 23, 42);
    doc.text(value, margin + 170, y);
    y += 26;
  }

  const year = new Date(data.date || Date.now()).getFullYear();

  row("Taxpayer Name:", data.name?.trim() || "Not set");
  row("TIN:", data.tin?.trim() || "Not set");
  row("Quarter:", `Q${data.quarter} ${year}`);
  row("Gross Receipts:", PESO(data.gross));
  row("Tax Rate:", "3%");

  y += 6;
  doc.setDrawColor(30, 41, 59);
  doc.line(margin, y, pageWidth - margin, y);
  y += 34;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(15, 23, 42);
  doc.text("TAX DUE", margin, y);
  doc.setFontSize(20);
  doc.setTextColor(34, 197, 94);
  const dueText = PESO(data.taxDue);
  const dueWidth = doc.getTextWidth(dueText);
  doc.text(dueText, pageWidth - margin - dueWidth, y);

  y += 70;
  doc.setDrawColor(148, 163, 184);
  doc.line(margin, y, margin + 220, y);
  y += 14;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text("Taxpayer signature over printed name", margin, y);

  y += 44;
  const generatedOn = new Date(data.date || Date.now()).toLocaleDateString("en-PH", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  doc.setFontSize(8);
  doc.text(
    doc.splitTextToSize(
      `Generated by Axla on ${generatedOn}. This is a quick reference preview, not an official BIR form — always confirm with eBIRForms/eFPS before filing.`,
      pageWidth - margin * 2,
    ),
    margin,
    y,
  );

  return doc.output("blob");
}
