// BIR Revenue District Office list, as supplied by the user from the
// official BIR directory. Kept as a single source of truth so the Settings
// dropdown always matches this exact data — do not hand-edit entries here
// without updating against the real BIR directory.
export interface RdoOption {
  code: string;
  name: string;
}

export const RDO_LIST: RdoOption[] = [
  { code: "001", name: "Laoag City, Ilocos Norte" },
  { code: "002", name: "Vigan, Ilocos Sur" },
  { code: "003", name: "San Fernando, La Union" },
  { code: "004", name: "Calasiao, West Pangasinan" },
  { code: "005", name: "Alaminos, Pangasinan" },
  { code: "006", name: "Urdaneta, Pangasinan" },
  { code: "007", name: "Bangued, Abra" },
  { code: "008", name: "Baguio City" },
  { code: "009", name: "La Trinidad, Benguet" },
  { code: "010", name: "Bontoc, Mt. Province" },
  { code: "011", name: "Tabuk City, Kalinga" },
  { code: "012", name: "Lagawe, Ifugao" },
  { code: "013", name: "Tuguegarao, Cagayan" },
  { code: "014", name: "Bayombong, Nueva Vizcaya" },
  { code: "015", name: "Naguilian, Isabela" },
  { code: "016", name: "Cabarroguis, Quirino" },
  { code: "17A", name: "Tarlac City, Tarlac" },
  { code: "17B", name: "Paniqui, Tarlac" },
  { code: "018", name: "Olongapo City" },
  { code: "019", name: "Subic Bay Freeport Zone" },
  { code: "020", name: "Balanga, Bataan" },
  { code: "21A", name: "North Pampanga" },
  { code: "21B", name: "South Pampanga" },
  { code: "21C", name: "Clark Freeport Zone" },
  { code: "022", name: "Baler, Aurora" },
  { code: "23A", name: "North Nueva Ecija" },
  { code: "23B", name: "South Nueva Ecija" },
  { code: "024", name: "Valenzuela City" },
  { code: "25A", name: "West Bulacan - Plaridel" },
  { code: "25B", name: "East Bulacan - Sta. Maria" },
  { code: "026", name: "Malabon-Navotas" },
  { code: "027", name: "Caloocan City" },
  { code: "028", name: "Novaliches" },
  { code: "029", name: "Tondo - San Nicolas" },
  { code: "030", name: "Binondo" },
  { code: "031", name: "Sta. Cruz" },
  { code: "032", name: "Quiapo-Sampaloc" },
  { code: "033", name: "Intramuros-Ermita-Malate" },
  { code: "034", name: "Paco-Pandacan-Sta. Ana" },
  { code: "038", name: "North Quezon City" },
  { code: "039", name: "South Quezon City" },
  { code: "040", name: "Cubao" },
  { code: "041", name: "Mandaluyong City" },
  { code: "042", name: "San Juan" },
  { code: "043", name: "Pasig" },
  { code: "044", name: "Taguig-Pateros" },
  { code: "045", name: "Marikina" },
  { code: "046", name: "Cainta-Taytay" },
  { code: "047", name: "East Makati" },
  { code: "048", name: "West Makati" },
  { code: "049", name: "North Makati" },
  { code: "050", name: "South Makati" },
  { code: "051", name: "Pasay City" },
  { code: "052", name: "Parañaque" },
  { code: "53A", name: "Las Piñas City" },
  { code: "53B", name: "Muntinlupa City" },
  { code: "54A", name: "Trece Martirez City, East Cavite" },
  { code: "54B", name: "Kawit, West Cavite" },
  { code: "055", name: "San Pablo City" },
  { code: "056", name: "Calamba, Laguna" },
  { code: "057", name: "Biñan, Laguna" },
  { code: "058", name: "Batangas City" },
  { code: "059", name: "Lipa City" },
  { code: "060", name: "Lucena City" },
  { code: "061", name: "Gumaca, Quezon" },
  { code: "062", name: "Boac, Marinduque" },
  { code: "063", name: "Calapan, Oriental Mindoro" },
  { code: "064", name: "Daet, Camarines Norte" },
  { code: "065", name: "Naga City" },
  { code: "066", name: "Iriga City" },
  { code: "067", name: "Legazpi City, Albay" },
  { code: "068", name: "Sorsogon, Sorsogon" },
  { code: "069", name: "Virac, Catanduanes" },
  { code: "070", name: "Masbate, Masbate" },
  { code: "071", name: "Kalibo, Aklan" },
  { code: "072", name: "Roxas City" },
  { code: "073", name: "San Jose, Antique" },
  { code: "074", name: "Iloilo City" },
  { code: "075", name: "Zarraga, Iloilo" },
  { code: "076", name: "Victorias City, Negros Occidental" },
  { code: "077", name: "Bacolod City" },
  { code: "078", name: "Binalbagan, Negros Occidental" },
  { code: "079", name: "Dumaguete City" },
  { code: "080", name: "Mandaue City" },
  { code: "081", name: "Cebu City North" },
  { code: "082", name: "Cebu City South" },
  { code: "083", name: "Talisay City, Cebu" },
  { code: "084", name: "Tagbilaran City" },
  { code: "085", name: "Catarman, Northern Samar" },
  { code: "086", name: "Borongan, Eastern Samar" },
  { code: "087", name: "Calbayog City, Samar" },
  { code: "088", name: "Tacloban City" },
  { code: "089", name: "Ormoc City" },
  { code: "090", name: "Maasin, Southern Leyte" },
  { code: "091", name: "Dipolog City" },
  { code: "092", name: "Pagadian City" },
  { code: "093A", name: "Zamboanga City" },
  { code: "093B", name: "Ipil, Zamboanga Sibugay" },
  { code: "094", name: "Isabela, Basilan" },
  { code: "095", name: "Jolo, Sulu" },
  { code: "096", name: "Bongao, Tawi-Tawi" },
  { code: "097", name: "Gingoog City" },
  { code: "098", name: "Cagayan de Oro City" },
  { code: "099", name: "Malaybalay City, Bukidnon" },
  { code: "100", name: "Ozamis City" },
  { code: "101", name: "Iligan City" },
  { code: "102", name: "Marawi City" },
  { code: "103", name: "Butuan City" },
  { code: "104", name: "Bayugan City, Agusan del Sur" },
  { code: "105", name: "Surigao City" },
  { code: "106", name: "Tandag, Surigao del Sur" },
  { code: "107", name: "Cotabato City" },
  { code: "108", name: "Kidapawan, North Cotabato" },
  { code: "109", name: "Tacurong, Sultan Kudarat" },
  { code: "110", name: "General Santos City" },
  { code: "111", name: "Koronadal City, South Cotabato" },
  { code: "112", name: "Tagum, Davao del Norte" },
  { code: "113A", name: "West Davao City" },
  { code: "113B", name: "East Davao City" },
  { code: "114", name: "Mati, Davao Oriental" },
  { code: "115", name: "Digos, Davao del Sur" },
];
