"use client";

import { useState } from "react";
import Link from "next/link";
import { FileText, Download, Loader2 } from "lucide-react";
import { generate2551QDat } from "@/lib/bir/ebirforms-2551q";
import { generate1701QDat } from "@/lib/bir/ebirforms-1701q";

interface GcashSummary {
  gross: number;
  tax: number;
  taxRate?: number;
}

export interface DownloadBirFilesProps {
  quarter?: number;
  year?: number;
  /** Real current-quarter figures for the 2551Q row — omit to show a clearly-labeled sample instead. */
  gcashSummary?: GcashSummary;
  /** Real year-to-date gross for the 1701Q row — omit to show a clearly-labeled sample instead. */
  annualGross?: number;
  tin?: string | null;
  rdoCode?: string | null;
  taxpayerName?: string | null;
}

const PESO = (n: number) => `₱${n.toLocaleString(undefined, { maximumFractionDigits: 0 })}`;
const PESO_K = (n: number) => (n >= 1000 ? `₱${Math.round(n / 1000)}k` : PESO(n));

const SAMPLE_2551Q = { gross: 125_000, tax: 3_750, taxRate: 0.03 };
const SAMPLE_1701Q_ANNUAL = 250_000;

function downloadTextFile(content: string, fileName: string, mimeType: string) {
  const blob = new Blob([content], { type: `${mimeType};charset=utf-8` });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = fileName;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

interface ReferenceSheetField {
  label: string;
  value: string;
}

/** Simple one-page reference PDF — a plain field list, not a facsimile of the real BIR form (that's what /dashboard/forms's official PDF already generates). Exists purely so this card's "Download PDF" button has something concrete backing it. */
async function downloadReferencePdf(title: string, subtitle: string, fields: ReferenceSheetField[], fileName: string) {
  const { default: jsPDF } = await import("jspdf");
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 40;

  doc.setFillColor(11, 15, 26); // #0B0F1A
  doc.rect(0, 0, pageWidth, 92, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(0, 255, 136);
  doc.text("AXLA", margin, 40);
  doc.setFontSize(11);
  doc.setTextColor(255, 255, 255);
  doc.text(title, margin, 62);
  doc.setFontSize(8.5);
  doc.setTextColor(148, 163, 184);
  doc.text(subtitle, margin, 78);

  let y = 130;
  for (const field of fields) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.setTextColor(100, 116, 139);
    doc.text(field.label, margin, y);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(15, 23, 42);
    doc.text(field.value, margin + 200, y);
    y += 26;
  }

  y += 20;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  const disclaimer = doc.splitTextToSize(
    "This is a structured reference sheet generated by Axla — not an official BIR document. Filing is done via the real eBIRForms/eFPS app or eAFS; use this sheet to fill in or double-check fields there, and always re-verify with your RDO before submitting.",
    pageWidth - margin * 2,
  );
  doc.text(disclaimer, margin, y);

  doc.save(fileName);
}

interface BirRowConfig {
  key: "2551Q" | "1701Q";
  label: string;
  isSample: boolean;
  gross: number;
  tax: number;
  taxRate: number;
  extraLabel: string; // e.g. "8% rate" or "YTD"
}

function BirFileRow({ row, meta }: { row: BirRowConfig; meta: { tin: string; rdo: string; name: string; quarter: number; year: number } }) {
  const [downloading, setDownloading] = useState<"dat" | "pdf" | null>(null);

  function handleDownloadDat() {
    setDownloading("dat");
    try {
      if (row.key === "2551Q") {
        const result = generate2551QDat({
          tin: meta.tin,
          rdo: meta.rdo,
          name: meta.name,
          quarter: meta.quarter,
          year: meta.year,
          grossSales: row.gross,
          taxRate: row.taxRate,
          taxDue: row.tax,
        });
        // eslint-disable-next-line no-console
        console.log("Axla BIR reference — JSON debug (2551Q):", result.jsonDebug);
        downloadTextFile(result.datContent, result.fileName, "text/plain");
      } else {
        const result = generate1701QDat({
          tin: meta.tin,
          rdo: meta.rdo,
          name: meta.name,
          quarter: meta.quarter,
          year: meta.year,
          grossSales: row.gross,
          taxableIncome: row.gross,
          taxRate: row.taxRate === 0.08 ? 0.08 : "graduated",
          taxDue: row.tax,
        });
        // eslint-disable-next-line no-console
        console.log("Axla BIR reference — JSON debug (1701Q):", result.jsonDebug);
        downloadTextFile(result.datContent, result.fileName, "text/plain");
      }
    } finally {
      setDownloading(null);
    }
  }

  async function handleDownloadPdf() {
    setDownloading("pdf");
    try {
      await downloadReferencePdf(
        `${row.key} Reference Sheet`,
        "Structured reference — not an official BIR document. Verify in eBIRForms before submitting.",
        [
          { label: "Taxpayer Name:", value: meta.name || "Not set" },
          { label: "TIN:", value: meta.tin || "Not set" },
          { label: "RDO Code:", value: meta.rdo || "Not set" },
          { label: "Period:", value: `Q${meta.quarter} ${meta.year}` },
          { label: "Gross:", value: PESO(row.gross) },
          { label: `Tax Rate:`, value: row.key === "2551Q" ? `${Math.round(row.taxRate * 100)}%` : row.taxRate === 0.08 ? "8% Flat" : "Graduated" },
          { label: "Tax Due:", value: PESO(row.tax) },
        ],
        `${row.key}_Q${meta.quarter}_${meta.year}_Axla_Reference.pdf`,
      );
    } finally {
      setDownloading(null);
    }
  }

  return (
    <div className="flex flex-col gap-3 rounded-lg border border-[#1F2A3A] bg-[#0F172A] p-4 transition hover:border-[#00FF88]/20 sm:flex-row sm:items-center sm:justify-between">
      <div className="flex items-center gap-3">
        <FileText className="h-5 w-5 shrink-0 text-[#00FF88]" />
        <div>
          <p className="text-sm font-medium text-white">{row.label}</p>
          <p className="text-xs text-gray-400">
            {row.isSample && <span className="mr-1.5 rounded bg-white/5 px-1.5 py-0.5 text-[10px] font-bold uppercase text-gray-400">Sample</span>}
            Gross {PESO_K(row.gross)} • Tax {PESO(row.tax)} • {row.extraLabel}
          </p>
        </div>
      </div>
      <div className="flex shrink-0 gap-2">
        <button
          type="button"
          onClick={handleDownloadDat}
          disabled={downloading !== null}
          className="flex items-center gap-1.5 rounded-lg bg-[#00FF88] px-4 py-2 text-xs font-bold text-black transition hover:bg-[#00FF88]/90 disabled:opacity-60"
        >
          {downloading === "dat" ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <Download className="h-3.5 w-3.5" />}
          Download .DAT
        </button>
        <button
          type="button"
          onClick={handleDownloadPdf}
          disabled={downloading !== null}
          className="flex items-center gap-1.5 rounded-lg border border-[#2D3A4A] bg-[#1E293B] px-4 py-2 text-xs font-medium text-white transition hover:bg-[#243146] disabled:opacity-60"
        >
          {downloading === "pdf" ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <Download className="h-3.5 w-3.5" />}
          Download PDF
        </button>
      </div>
    </div>
  );
}

const HOW_TO_FILE_STEPS = [
  "Download the .DAT (or PDF) reference from Axla.",
  "Open the real BIR eBIRForms app (bir.gov.ph) and pull up the matching form for this quarter.",
  "Use the reference to fill in — or double-check — each field, then let eBIRForms validate the numbers.",
  "Submit via eBIRForms/eFPS or email to esubmission@bir.gov.ph (or eAFS, if applicable), then pay via your usual channel.",
];

export function DownloadBirFiles({ quarter, year, gcashSummary, annualGross, tin, rdoCode, taxpayerName }: DownloadBirFilesProps) {
  const now = new Date();
  const q = quarter ?? Math.floor(now.getMonth() / 3) + 1;
  const y = year ?? now.getFullYear();

  const meta = {
    tin: tin || "",
    rdo: rdoCode || "",
    name: taxpayerName || "",
    quarter: q,
    year: y,
  };

  const row2551Q: BirRowConfig = gcashSummary
    ? {
        key: "2551Q",
        label: `2551Q Q${q} ${y}`,
        isSample: false,
        gross: gcashSummary.gross,
        tax: gcashSummary.tax,
        taxRate: gcashSummary.taxRate ?? 0.03,
        extraLabel: `${Math.round((gcashSummary.taxRate ?? 0.03) * 100)}% rate`,
      }
    : {
        key: "2551Q",
        label: `2551Q Q${q} ${y}`,
        isSample: true,
        gross: SAMPLE_2551Q.gross,
        tax: SAMPLE_2551Q.tax,
        taxRate: SAMPLE_2551Q.taxRate,
        extraLabel: `${Math.round(SAMPLE_2551Q.taxRate * 100)}% rate`,
      };

  const row1701Q: BirRowConfig = annualGross
    ? {
        key: "1701Q",
        label: `1701Q Q${q} ${y}`,
        isSample: false,
        gross: annualGross,
        tax: Math.round(annualGross * 0.08 * 100) / 100,
        taxRate: 0.08,
        extraLabel: "YTD",
      }
    : {
        key: "1701Q",
        label: `1701Q Q${q} ${y}`,
        isSample: true,
        gross: SAMPLE_1701Q_ANNUAL,
        tax: Math.round(SAMPLE_1701Q_ANNUAL * 0.08 * 100) / 100,
        taxRate: 0.08,
        extraLabel: "YTD",
      };

  const anySample = row2551Q.isSample || row1701Q.isSample;

  return (
    <div className="relative overflow-hidden rounded-xl border border-[#1E293B] bg-[#141A2A] p-6">
      <div className="pointer-events-none absolute -top-24 left-1/2 h-48 w-[120%] -translate-x-1/2 rounded-full bg-[#00FF88]/20 blur-[80px]" />

      <div className="relative flex flex-wrap items-start justify-between gap-3">
        <div>
          <h2 className="text-base font-bold text-white">BIR-Ready Files — No manual encoding</h2>
          <p className="mt-1 text-xs text-gray-400">Generated from your GCash history — Axla&apos;s structured reference format</p>
        </div>
        <span className="rounded border border-yellow-800/30 bg-yellow-900/20 px-2 py-1 text-xs text-yellow-400">REFERENCE</span>
      </div>

      <div className="relative mt-5 flex flex-col gap-4">
        <BirFileRow row={row2551Q} meta={meta} />
        <BirFileRow row={row1701Q} meta={meta} />
      </div>

      {anySample && (
        <div className="relative mt-4 flex flex-wrap items-center justify-between gap-2 rounded-lg border border-[#1E293B] bg-white/[0.02] px-4 py-3">
          <p className="text-xs text-gray-400">Sample preview shown above — upload your GCash history to generate your real files.</p>
          <Link
            href="/dashboard/upload"
            className="shrink-0 rounded-lg bg-[#00FF88]/10 px-3 py-1.5 text-xs font-semibold text-[#00FF88] transition hover:bg-[#00FF88]/20"
          >
            Upload GCash to generate your files →
          </Link>
        </div>
      )}

      <div className="relative mt-6 rounded-lg border border-[#1E293B] bg-[#0F172A] p-4">
        <p className="mb-3 text-sm font-bold text-white">How to file (official BIR channels):</p>
        <ol className="space-y-2.5">
          {HOW_TO_FILE_STEPS.map((step, i) => (
            <li key={step} className="flex items-start gap-2.5 text-xs text-gray-300">
              <span className="flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-[#00FF88]/15 text-[10px] font-bold text-[#00FF88]">
                {i + 1}
              </span>
              {step}
            </li>
          ))}
        </ol>
      </div>

      <p className="relative mt-4 border-t border-[#1E293B] pt-3 text-[11px] leading-relaxed text-gray-500">
        Axla generates BIR-ready reference sheets and auto-fill files — it does not submit filings on your behalf. Filing
        happens via official BIR eBIRForms/eFPS/eAFS channels. Axla is not yet an accredited BIR EIS provider — we&apos;re
        working on it. Always verify figures with your RDO or accountant before submitting.
      </p>
    </div>
  );
}
