"use client";

import { jsPDF } from "jspdf";

export interface PayslipData {
  businessName: string;
  staffName: string;
  dailyRate: number;
  daysPresent: number;
  basicPay: number;
  gcash: string | null;
  /** Free-tier preview — stamps a diagonal DEMO watermark across the page so it can't be mistaken for a real payslip. */
  demo: boolean;
}

const PESO = (n: number) => `P ${n.toLocaleString(undefined, { maximumFractionDigits: 2 })}`;

/** Client-side only (jsPDF, no server round-trip) — triggers an immediate browser download. */
export function generatePayslipPdf(data: PayslipData): void {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 40;

  // Header
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(0, 26, 41);
  doc.text("AXLA", margin, 55);
  doc.setTextColor(0, 200, 120);
  doc.text(" PAYROLL", margin + doc.getTextWidth("AXLA"), 55);

  doc.setDrawColor(0, 200, 120);
  doc.setLineWidth(1.5);
  doc.line(margin, 68, pageWidth - margin, 68);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(120, 120, 120);
  doc.text(new Date().toLocaleDateString("en-PH", { year: "numeric", month: "long", day: "numeric" }), pageWidth - margin, 30, { align: "right" });

  // Title
  let y = 100;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.setTextColor(20, 20, 20);
  doc.text("Payslip", margin, y);
  y += 20;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(60, 60, 60);
  doc.text(data.businessName, margin, y);
  y += 30;

  // Details box
  doc.setDrawColor(230, 230, 230);
  doc.setFillColor(248, 250, 249);
  doc.roundedRect(margin, y, pageWidth - margin * 2, 90, 6, 6, "FD");
  const labelX = margin + 16;
  const valueX = margin + 180;
  let rowY = y + 24;
  const rows: [string, string][] = [
    ["Employee:", data.staffName],
    ["Days Present:", String(data.daysPresent)],
    ["Daily Rate:", PESO(data.dailyRate)],
    ["GCash Number:", data.gcash ?? "Not set"],
  ];
  doc.setFontSize(10);
  for (const [label, value] of rows) {
    doc.setFont("helvetica", "normal");
    doc.setTextColor(130, 130, 130);
    doc.text(label, labelX, rowY);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(20, 20, 20);
    doc.text(value, valueX, rowY);
    rowY += 18;
  }
  y += 110;

  // Breakdown
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(20, 20, 20);
  doc.text("Breakdown", margin, y);
  y += 18;

  const breakdown: [string, string][] = [
    ["Basic Pay", PESO(data.basicPay)],
    ["Overtime", PESO(0)],
    ["Deductions", PESO(0)],
  ];
  doc.setFontSize(10);
  for (const [label, value] of breakdown) {
    doc.setFont("helvetica", "normal");
    doc.setTextColor(90, 90, 90);
    doc.text(label, labelX, y);
    doc.text(value, pageWidth - margin - 16, y, { align: "right" });
    y += 16;
  }

  y += 4;
  doc.setDrawColor(220, 220, 220);
  doc.line(margin, y, pageWidth - margin, y);
  y += 20;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(20, 20, 20);
  doc.text("Net Pay", labelX, y);
  doc.setTextColor(0, 170, 100);
  doc.text(PESO(data.basicPay), pageWidth - margin - 16, y, { align: "right" });

  // Footer disclaimer
  const footerY = doc.internal.pageSize.getHeight() - 40;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(150, 150, 150);
  doc.text(
    "Generated by Axla Payroll — basic pay only in this phase, no overtime or statutory deductions computed. Not a substitute for BIR/DOLE-compliant payroll software.",
    margin,
    footerY,
    { maxWidth: pageWidth - margin * 2 },
  );

  if (data.demo) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(60);
    doc.setTextColor(230, 60, 60);
    const centerX = pageWidth / 2;
    const centerY = doc.internal.pageSize.getHeight() / 2;
    doc.saveGraphicsState();
    // jsPDF doesn't expose a direct opacity setter pre-2.x GState-free API in
    // some builds — GState is the documented way to get translucency.
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const gState = new (doc as any).GState({ opacity: 0.25 });
    doc.setGState(gState);
    doc.text("DEMO", centerX, centerY, { angle: 30, align: "center" });
    doc.restoreGraphicsState();
  }

  const filenameSafe = data.staffName.replace(/[^a-zA-Z0-9]+/g, "_").slice(0, 40) || "Staff";
  doc.save(`Payslip_${filenameSafe}${data.demo ? "_DEMO" : ""}.pdf`);
}
