import Link from "next/link";

export const metadata = { title: "Privacy Policy — Axla" };

export default function PrivacyPage() {
  return (
    <main className="mx-auto max-w-2xl px-4 py-16 sm:px-6">
      <Link href="/" className="text-sm font-semibold text-accent-dark">
        ← Back to Axla
      </Link>
      <h1 className="mt-6 text-3xl font-extrabold text-navy">Privacy Policy</h1>
      <p className="mt-2 text-sm text-slate-500">Last updated: July 2026</p>

      <p className="mt-6 text-slate-600">
        Axla ("we," "us") operates axla.space, including TaxLaya, our AI
        chat assistant for BIR tax questions. This policy explains what we
        collect, why, and how it's handled. We're a small, pre-launch team —
        this is written in plain language, not legalese, and describes
        exactly what the product does today.
      </p>

      <h2 className="mt-8 text-lg font-bold text-navy">What we collect</h2>
      <ul className="mt-3 list-disc space-y-2 pl-5 text-slate-600">
        <li>
          <strong>Waitlist signups:</strong> your email address and your
          answer to "gaano ka-hassle ang BIR sa'yo?" (1–10). Used only to
          notify you about Axla and understand demand — never sold or shared.
        </li>
        <li>
          <strong>TaxLaya chat messages:</strong> we log the questions you
          send TaxLaya (not its replies) along with your IP address, to
          measure usage, enforce the daily message limit, and improve the
          product. We do not require an account or ask for your name to use
          the chat.
        </li>
        <li>
          <strong>Local storage on your device:</strong> your sound
          on/off preference for the chat widget. This stays in your browser
          and isn't sent to us.
        </li>
      </ul>

      <h2 className="mt-8 text-lg font-bold text-navy">Third parties</h2>
      <p className="mt-3 text-slate-600">
        TaxLaya's replies are generated by{" "}
        <a
          href="https://openai.com/policies/privacy-policy"
          className="text-accent-dark underline"
          target="_blank"
          rel="noopener noreferrer"
        >
          OpenAI
        </a>
        . Your messages are sent to OpenAI's API to produce a response,
        subject to their privacy policy. Our database and backend run on{" "}
        <a
          href="https://supabase.com/privacy"
          className="text-accent-dark underline"
          target="_blank"
          rel="noopener noreferrer"
        >
          Supabase
        </a>
        . We don't use any other analytics or advertising trackers beyond
        what's disclosed here.
      </p>

      <h2 className="mt-8 text-lg font-bold text-navy">What we don't do</h2>
      <p className="mt-3 text-slate-600">
        We never sell your data. We don't use your chat questions or email
        for advertising. We don't share individual records with anyone
        outside the OpenAI/Supabase processing described above.
      </p>

      <h2 className="mt-8 text-lg font-bold text-navy">Your rights</h2>
      <p className="mt-3 text-slate-600">
        Email us to request a copy of your data or ask us to delete your
        waitlist signup. Since chat messages aren't tied to an account or
        email, we identify them by IP address on request.
      </p>

      <p className="mt-8 text-sm text-slate-500">
        Axla is a pre-launch product. This policy reflects what the app
        actually does today and will be expanded (and reviewed by counsel)
        as we approach a full public launch.
      </p>

      <p className="mt-6 text-slate-600">
        Questions? Email us at{" "}
        <a href="mailto:hello@axla.space" className="text-accent-dark underline">
          hello@axla.space
        </a>
        .
      </p>
    </main>
  );
}
