import "server-only";
import JSZip from "jszip";

export interface RdoPacketFormFile {
  fileName: string; // without extension
  xmlContent?: string;
  datContent?: string;
}

export interface RdoPacketReceiptFile {
  fileName: string;
  bytes: Uint8Array;
}

export interface RdoPacketInput {
  taxpayerName: string;
  tin: string;
  rdoCode: string;
  quarter: number;
  year: number;
  gross: number;
  taxDue: number;
  forms: RdoPacketFormFile[];
  receipts: RdoPacketReceiptFile[];
  previewPdf?: Uint8Array;
}

const PESO = (n: number) => `PHP ${n.toLocaleString(undefined, { maximumFractionDigits: 2 })}`;

function buildTransmittalLetter(input: RdoPacketInput): string {
  const today = new Date().toLocaleDateString("en-PH", { year: "numeric", month: "long", day: "numeric" });
  return `AXLA — RDO FILING PACKET TRANSMITTAL
Generated: ${today}

Taxpayer: ${input.taxpayerName || "Not set"}
TIN: ${input.tin || "Not set"}
RDO Code: ${input.rdoCode || "Not set"}
Period: Q${input.quarter} ${input.year}
Gross: ${PESO(input.gross)}
Tax Due: ${PESO(input.taxDue)}

Contents of this packet:
${input.previewPdf ? "- BIR Form Preview PDF\n" : ""}${input.forms
    .flatMap((f) => [f.xmlContent ? `- ${f.fileName}.xml` : null, f.datContent ? `- ${f.fileName}.dat` : null])
    .filter(Boolean)
    .join("\n")}
${input.receipts.length > 0 ? `- ${input.receipts.length} receipt file(s)` : "- No receipts attached"}

IMPORTANT: The XML/DAT files in this packet are structured reference
exports of the figures Axla computed — NOT verified eBIRForms imports.
BIR's Offline eBIRForms desktop app does not publicly document a generic
file-import feature for third-party data. Use these files as a reference
or backup when filling out the real eBIRForms app, an accountant handoff,
or a manual cross-check — always re-verify all figures in eBIRForms (or
with your accountant) before submitting to the BIR.

— Generated by Axla (axla.space)
`;
}

/**
 * Bundles a BIR form preview PDF, one or more XML/DAT reference exports,
 * any receipts on file for the period, and a plain-text transmittal cover
 * letter into a single ZIP for download. Pure packaging — every file
 * inside was already generated/validated by its own module; this doesn't
 * add any new BIR-compliance claims beyond what those generators already
 * make (see each ebirforms-*.ts file's own disclaimer).
 */
export async function buildRdoPacketZip(input: RdoPacketInput): Promise<Uint8Array> {
  const zip = new JSZip();

  if (input.previewPdf) {
    zip.file(`BIR-Form-Preview-Q${input.quarter}-${input.year}.pdf`, input.previewPdf);
  }

  const formsFolder = zip.folder("BIR-Forms");
  for (const form of input.forms) {
    if (form.xmlContent) formsFolder?.file(`${form.fileName}.xml`, form.xmlContent);
    if (form.datContent) formsFolder?.file(`${form.fileName}.dat`, form.datContent);
  }

  if (input.receipts.length > 0) {
    const receiptsFolder = zip.folder("Receipts");
    for (const receipt of input.receipts) {
      receiptsFolder?.file(receipt.fileName, receipt.bytes);
    }
  }

  zip.file("Transmittal-Cover-Letter.txt", buildTransmittalLetter(input));

  const buffer = await zip.generateAsync({ type: "uint8array" });
  return buffer;
}
